apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-test-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgBl5ZzCcgs+u5LAaixb2dVFfR3mHpS8ZNoUty591KmV0dZciir+thUOY3vow6EAtaf1KJTKNdl/9VyFdst9i00Lv72l4D0tvPKvZIQS1KIdOsq15WU+dSPgoCuLI27LoRJv0hK4D/ZLs0dVsV9LUTTDqQwcDHUMHPNgyEEljd9JRgWR7NZWhuglnuCjSlMBSESQLWeIafl3SrPfJgh5yGt3R9HxuVytb3IAsZc1Wp4J2Y0h3WF/v8z5CCrCLIM1CDNXKySRnqbp/2Ufq6s00r62UY/ZoqFoaqE4Ufk9d7qSYamNpWM7a0u4Osz5LAsKIykaudr0nJkRLtTs67ZE2byZ5c2ax+ZgbCdf0Nrc2CFKMQ72GgTagHBflsVtSVlCOcJeDLvFsib7wluaKzLpuc32/H8tQhR09Zol10eyGUsMhnag5gc/MY9S/twtY35+ArRie8rWcw0Dg0tzBhlz/NqTyFSnpO9VJ9LZq8biI3F65PtQ7YRfBZxDMUNh2Ail2alZ77Ev5A3oAvnaCqZoewG2iYUiOt630IfqjkRqGt2FoQzhTWc+YGwp0pQiAWc8AEPxTipTUhE8JDkCnNieIZTRgmcLarr9sZbR8r3kRkvaJiVluZ5o8spD8RA3+GB4OeswilKKuKbLv8Bb7/t2r+gwo1wRJ/c5lQQsjMjtF6mutcYE5rJ1ss172LsapoClaepfdLyaVXzkWVEA
  template:
    metadata:
      creationTimestamp: null
      name: sealed-test-secret
      namespace: default
